version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend1
      - backend2
      # - backend3
      # - backend4
      # - backend5
      # - backend6
      # - backend7
      # - backend8
      # - backend9
      # - backend10
    networks:
      - my-network

  backend1:
    build: ./backend
    volumes:
      - shared-backend-data:/backend
    ports:
      - "5001:5000"
    networks:
      - my-network

  backend2:
    build: ./backend
    volumes:
      - shared-backend-data:/backend
    ports:
      - "5002:5000"
    networks:
      - my-network

  # Uncomment and repeat for backend3 to backend10
  # backend3:
  #   build: ./backend
  #   volumes:
  #     - shared-backend-data:/backend
  #   ports:
  #     - "5003:5000"
  #   networks:
  #     - my-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - my-network
    environment:
      - REACT_FRONTEND_URL=http://frontend:80
      - REACT_BACKEND_URL=http://backend:5000
    depends_on:
      - frontend
      - backend1
      - backend2
      # - backend3
      # - backend4
      # - backend5
      # - backend6
      # - backend7
      # - backend8
      # - backend9
      # - backend10

networks:
  my-network:
    external: true

volumes:
  shared-backend-data:
